Have --with-pythonbindir configure option check for executable

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3047,6 +3047,10 @@ if test "x$jh_with_pythonbindir" = "xno"; then
    SDPC_PYTHON_BINDIR=""
 else
    SDPC_PYTHON_BINDIR="$jh_with_pythonbindir"
+   if test -n "$SDPC_PYTHON_BINDIR" -a ! -x "$SDPC_PYTHON_BINDIR/python3" ; then
+      echo "ERROR: python3 executable not found in pythonbindir=$jh_with_pythonbindir"
+      exit 1
+   fi
 fi
 
 
